### ISSUE TITLE
ESDM deployment checklist

### ISSUE THREAD

**Issue by cygnusv** [threshold-network/solidity-contracts#69]
# Prerequisites 
- [x] NU community decision on ESDM (https://snapshot.org/#/nudao.eth/proposal/0x08474ef5aa3ee61e2e08d60539dbc9abe40f6057ad7e25183d62d9457f9b4586)
- [x] KEEP community decision on ESDM (https://snapshot.org/#/keepstakers.eth/proposal/0x14457cbbdaf165cea48ecd26f21f03d6bec73a08a6a1cf10ae8c04c4f60caba4)
- [ ] ESDM signers and addresses:
  - Piotr Dyraga, Keep Network: `0x4A441697234bdCE62ede26345A443924Be7cEE4d`
  - Kuba Nowakowski, Keep Network: `0xcB38B8c0385C869F05108220647f4b8e7b364d6d`
  - MacLane Wilkison, NuCypher: TBD
  - David Nuñez, NuCypher: TBD

# Steps
- [ ] Set up Emergency Security Developer Multisig (ESDM) contract (address: `0xTBD`) with above signers and 4/4 threshold.
  - ESDM contract address: `0xTBD`
- [ ] ESDM signed TX lowering threshold from 4/4 to 3/4
  - TX: TBD

**Comment by pdyraga** [comment]
`0x4A441697234bdCE62ede26345A443924Be7cEE4d`

**Comment by nkuba** [comment]
`0xcB38B8c0385C869F05108220647f4b8e7b364d6d`

**Comment by mswilkison** [comment]
0xb195a8CF4898E6DDc92e435cb118E9842456A45A

**Comment by cygnusv** [comment]
`0x7b45AAD93caBCEeC109f3Fec77EDDf5f6438f1D7`

**Comment by mswilkison** [comment]
Maybe a useful reference and recommended exercises for us to go through at some point: https://twitter.com/storming0x/status/1509769575021178886

**Comment by cygnusv** [comment]
Yep, definitely. Tbh, that tweet is what made me remember we still had this issue open 😅, although, to be fair, the ESDM has currently no way to do anything on the staking smart contract. In any case, that tweet made me start a document for an emergency security process but it's still WIP. I'll share for discussion soon.

**Comment by mswilkison** [comment]
Closing as not planned. The existing Threshold Council arrangement is accepted, so the separate 3-of-4 ESDM deployment and threshold-change transaction proposed in this checklist are no longer needed.

The Council address, `0x9F6e831c8F8939DC0C830C6e492e7cEf4f9C2F5f`, is assigned to the mainnet `esdm` role in both the [tBTC configuration](https://github.com/threshold-network/tbtc-v2/blob/502cd3982b5b2dc3ff0e1e6085a24502f78cfe26/solidity/hardhat.config.ts#L238) and the [Keep ECDSA configuration](https://github.com/threshold-network/keep-core/blob/a7ac8989b662d51d8a94fa28f1ac226058d5d6cc/solidity/ecdsa/hardhat.config.ts).
